### ISSUE TITLE
Cannot install plugins via GUI on rpi zero wireless

### ISSUE THREAD

**Issue by mymike00** [nymea/nymea-update-plugin-packagekit#11]
I tried to install a new plugin. System settings -> Software update -> Install or remove software -> select a plugin -> Install. The update screen appears and stays there for a while. When it disappears I go to the same plugin page and it is marked as not installed. I managed to install the plugin via apt, though

Logs are all similar to this one https://paste.ubuntu.com/p/FKfqBmDp8z/

When I installed the plugin via apt, the app showed the update animation if I try to open the updates page. When it finished, the plugin I installed via apt was listed as installed in the plugin list under the updates page. I had to restart nymea:core before I was able to add a onewire sensor (in this case), though. This is the nymea log while (and after) installing via apt https://paste.ubuntu.com/p/QPrSVQxDR5/

**Comment by mzanetti** [comment]
I am afraid the Pi Zero W has too little RAM for packagekit, which insanely resource intense...

**Comment by mzanetti** [comment]
Thanks for the report though... Normally we don't just dismiss issues just like that, but given Packagekit is *really* bad on resources and also it seems unmaintaied by now, I'm not sure we can do anything with reasonable effort. The proper solution would be to fix packagekit.

If you happen to know of an alternative to packagekit, let us know.

**Comment by mymike00** [comment]
Sure, no problem at all, given that there's a workaround available.
Unfortunately I don't know any alternatives to it.
